### ISSUE TITLE
Fatal error in: media/engine/webrtc_voice_engine.cc

### ISSUE THREAD

**Issue by ispysoftware** [pixiv/webrtc#11]
Had a crash report

```
#
# Fatal error in: ../../../../../../media/engine/webrtc_voice_engine.cc, line 246
# last system error: 14007
# Check failed: adm()
#
```

corresponding to:

```
#if defined(WEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE)
  // No ADM supplied? Create a default one.
  if (!adm_) {
    adm_ = webrtc::AudioDeviceModule::Create(
        webrtc::AudioDeviceModule::kPlatformDefaultAudio, task_queue_factory_);
  }
#endif  // WEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE
  RTC_CHECK(adm()); <-- bugging out here
```

PC running windows 10, has working sound card and drivers. adm is passed in as null (as in example code) so webrtc::AudioDeviceModule::Create is failing for some reason. 14007 is ERROR_SXS_KEY_NOT_FOUND. Quite possibly a missing dll on the client's computer. Thought i'd document it here.

**Comment by akihikodaki** [comment]
I could not find any issue mentioning 14007 or `ERROR_SXS_KEY_NOT_FOUND` at https://bugs.webrtc.org/. The cause should be identified and reported there if it is not in the modifications of this fork.
