### ISSUE TITLE
How is the jingle_peerconnection_so target specified? (unknown ninja target after upgrading to M86)

### ISSUE THREAD

**Issue by sebjf** [pixiv/webrtc#19]
Hi,

I am trying to merge [M86](https://groups.google.com/forum/#!topic/discuss-webrtc/pKCOpi9Llyc) (branch-heads/4240) and re-build, but after the merge Ninja can no longer find the jingle_peerconnection_so target.

In more detail:

I start with a working branch (a fork of branch-heads/pixiv-m78), then fetch and merge 4240:

```
webrtc-checkout/src> git fetch origin branch-heads/4240
webrtc-checkout/src> git merge branch-heads/4240
```

There are a number of conflicts resolved in favour of 4240.
I then issue gclient sync.

`webrtc-checkout> gclient sync`

I then give the build command.

`webrtc_checkout\src\sdk\dotnet\unity> dotnet build unity.msbuildproj`

This fails with the error

```
ninja : error : unknown target ':jingle_peerconnection_so' [\webrtc_checkout\src\sdk\dotnet\unity\unity.msbuildproj]
\webrtc_checkout\src\sdk\dotnet\unity\unity.msbuildproj(157,9): error MSB3073: The command "ninja -C "obj\\Debug\\"build/win_x64 :jingle_peerconnection_so" exited with code 1.
```

Indeed, in the `build.ninja` file in `obj\Debug\build\win_x64` I can confirm the target 

`build jingle_peerconnection_so: phony ./jingle_peerconnection_so.dll.lib`

is missing after regenerating.

I am pretty sure this issue is caused when merging the BUILD.gn files, but when I merge it is not obvious what creates this target and adds the c dependencies.

**What changes were made to the BUILD.gn files to support this fork?**

(PS. Apologies for creating an issue. I could not find a discussion tab or similar.)

Sj

**Comment by akihikodaki** [comment]
> I am pretty sure this issue is caused when merging the BUILD.gn files, but when I merge it is not obvious what creates this target and adds the c dependencies.

See https://github.com/pixiv/webrtc/commit/01c4ce0a73a747f0106a8d5d5eb45be3aab3365a#diff-4eaebbcd1dc0da11e3a3ce488290bfc6.

> (PS. Apologies for creating an issue. I could not find a discussion tab or similar.)

It is fine to open an issue for a question.
