### ISSUE TITLE
ICE functionality and datachannels

### ISSUE THREAD

**Issue by ispysoftware** [pixiv/webrtc#3]
The current code lets you get the ice candidate string to send to the client but not the sdpmid or sdpmlineindex values. I can't see a way of pushing an ICE candidate into the peer connection object from the client which is needed for ice negotiation.

Also I know you said wontfix for datachannels but it's quite a massive hole in the project and a show-stopper for us. There is this https://github.com/RainwayApp/spitfire which has done basically all of the work already, should just be a case of copying/ pasting the relevant interfaces. I'd do it but i'm not really a c++ guy and don't have a build system for the webrtc project.

**Comment by akihikodaki** [comment]
> Also I know you said wontfix for datachannels but it's quite a massive hole in the project and a show-stopper for us. There is this https://github.com/RainwayApp/spitfire which has done basically all of the work already, should just be a case of copying/ pasting the relevant interfaces. I'd do it but i'm not really a c++ guy and don't have a build system for the webrtc project.

You cannot just copy and paste the implementation. A language binding is all about interfaces, and the libraries have obviously different interfaces because they are written by different people. It is not possible to integrate them.

**Comment by ispysoftware** [comment]
ok, it's a start though, i'll look into it.

**Comment by ispysoftware** [comment]
I've looked into it. It's much more complicated than I was imagining. I've sorted out the ICE stuff but the data channel integration is beyond me. Adding a data channel on the client actually crashes the application by the way. If you added data channels to this it'd be the only proper cross platform solution for webrtc. Is there really no chance of that happening?

**Comment by ispysoftware** [comment]
Don't worry about it, got it sorted out
