### ISSUE TITLE
Call "deliverRecordedData" method with error "EXC_BAD_ACCESS"

### ISSUE THREAD

**Issue by shenfusheng** [pixiv/webrtc#30]
<img width="1139" alt="截屏2022-11-17 15 58 06" src="https://user-images.githubusercontent.com/9476838/202391444-2ff3d7c9-14d2-4bcc-8745-27fdc2c29181.png">
<img width="782" alt="截屏2022-11-17 16 08 57" src="https://user-images.githubusercontent.com/9476838/202391481-14b34166-4ac5-401d-ad4a-58cf3c664498.png">

Could you help me take a look, thank you very much.

**Comment by bbatuhandogan** [comment]
Hello, did you find any solution? I am having some problem. Thank you.

**Comment by shenfusheng** [comment]
你好，邮件已收到，谢谢！

**Comment by leokangmh** [comment]
Hey, I have same problem. Did you find any solution?

**Comment by shenfusheng** [comment]
你好，邮件已收到，谢谢！

**Comment by nmalevich** [comment]
Hey, I have same problem. Did you find any solution? Thank you

**Comment by shenfusheng** [comment]
你好，邮件已收到，谢谢！
