### ISSUE TITLE
audio not working

### ISSUE THREAD

**Issue by ispysoftware** [pixiv/webrtc#5]
I'm sending Audio in, it's correctly formatted but nothing is coming out the other side - looks like the RTP Audio stream isn't being hooked up properly to the MediaStreamTrack. Do you have this working in a web browser? (Got video and data channels working!)

![audio_issue](https://user-images.githubusercontent.com/800093/78358677-2d3b2480-75e6-11ea-8f74-f645e490f0f8.jpg)

**Comment by ispysoftware** [comment]
I'm not sure if it's a problem but you are using IVideo**Track**SourceInterface and IAudioSourceInterface here:

     public static DisposableAudioTrackInterface CreateAudioTrack(
            this IPeerConnectionFactoryInterface factory,
            string label,
            IAudioSourceInterface source)
        {
            return new DisposableAudioTrackInterface(
                Interop.AudioTrackInterface.ToWebrtcMediaStreamTrackInterface(
                    webrtcPeerConnectionFactoryInterfaceCreateAudioTrack(
                        factory.Ptr,
                        label,
                        source.Ptr
                    )
                )
            );
        }

        public static DisposableVideoTrackInterface CreateVideoTrack(
            this IPeerConnectionFactoryInterface factory,
            string label,
            IVideoTrackSourceInterface source)
        {
            return new DisposableVideoTrackInterface(
                Interop.VideoTrackInterface.ToWebrtcMediaStreamTrackInterface(
                    webrtcPeerConnectionFactoryInterfaceCreateVideoTrack(
                        factory.Ptr,
                        label,
                        source.Ptr
                    )
                )
            );
        }

**Comment by ispysoftware** [comment]
was an issue in client code

**Comment by darnfish** [comment]
> was an issue in client code

What was the issue?
