### ISSUE TITLE
Get raw encoded video frame

### ISSUE THREAD

**Issue by anchalsinha** [pixiv/webrtc#8]
I am working with the Unity plugin, and I can see that an I420 frame can be created from the raw Texture2D. Is it possible to get the raw encoded bytes of the H264 encoded frame that is sent over WebRTC? 
The DisposableVideoFrame object doesn't have any serializable properties that store the actual frame data. Am I looking in the wrong place?

**Comment by akihikodaki** [comment]
> Is it possible to get the raw encoded bytes of the H264 encoded frame that is sent over WebRTC?

No. You have to hack the underlying WebRTC library, which is out of scope for this project.

>  The DisposableVideoFrame object doesn't have any serializable properties that store the actual frame data. Am I looking in the wrong place?

The C# codes are dumb bindings; they have no states except pointers of underlying C++ values. You have to look at definitions of C++ values. `DisposableVideoFrame` represents `webrtc::VideoFrame`, and as you can see in the C++ definition, `webrtc::VideoFrame` is a structure combining metadata and `webrtc::VideoFrameBuffer`, which is the I420 frame you gave.
The interfaces WebRTC provides only deals with unencoded frames so you cannot extract H.264 encoded frame from `webrtc::VideoFrame` or any other values.
