### ISSUE TITLE
Adding ICE candidate in Unity plugin

### ISSUE THREAD

**Issue by anchalsinha** [pixiv/webrtc#9]
I have the basic signalling process setup in Unity, and am trying to add a remote ICE candidate to the local peer. However, I cannot see the AddIceCandidate method in the Unity API (which is present in the native WebRTC API). 
I took a look at your example Unity application, and saw the ICE candidate being sent in the OnIceCandidate callback, but nowhere was it being received and added.

Any insight would be appreciated.

**Comment by akihikodaki** [comment]
The example does not add a remote ICE candidate because it interacts with an SFU. The .NET binding, which is designed to be minimal to create the example, also lacks methods required for that purpose. The feature is certainly nice to have.

**Comment by akihikodaki** [comment]
Fixed with fc3c2f0fdb7d7abbe6c3e61adee79e6a9e551592.
